# Generated by Django 5.0.4 on 2024-05-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmetadata',
            name='description',
            field=models.TextField(max_length=150),
        ),
    ]
