# Generated by Django 5.0.4 on 2024-05-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_metadata', '0002_alter_blogmetadata_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmetadata',
            options={'verbose_name': 'Blog Metadata', 'verbose_name_plural': 'Blog Metadata Entries'},
        ),
        migrations.AlterField(
            model_name='blogmetadata',
            name='componentName',
            field=models.CharField(max_length=25),
        ),
    ]
