# Generated by Django 5.0.4 on 2024-06-24 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_metadata', '0004_remove_blogmetadata_componentname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogMetaData',
            new_name='Blog',
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
    ]
