# Generated by Django 5.0.4 on 2024-07-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_metadata', '0005_rename_blogmetadata_blog_alter_blog_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='route',
        ),
    ]
